name: Qiita記事取得_定期実行

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 3,9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # キャッシュ
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }} 
        restore-keys: npm-

    # インストール
    - name: npm install command
      run: npm install

    # 実際のコマンド
    - name: main action...
      run: ./node_modules/.bin/ts-node src/index.ts
      env:
        DISCORD_WEB_HOOK_URL: ${{ secrets.DISCORD_WEB_HOOK_URL }}
