name: 記事取得_定期実行

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "10 3,9 * * *"

jobs:
  zenn:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js with Volta
        uses: volta-cli/action@v1
        with:
          node-version: "20.18.0"

      - name: Install pnpm
        run: volta install pnpm@10.0.0

      - name: Install dependencies
        run: pnpm install

      - name: zenn main action...
        run: pnpm ts-node -r tsconfig-paths/register src/zenn/index.ts
        env:
          DISCORD_WEB_HOOK_URL_FOR_ZENN: ${{ secrets.DISCORD_WEB_HOOK_URL_FOR_ZENN }}
